language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - cp app/config/.env.default app/config/.env
  - composer install
  - if php -v | grep -q "PHP 5.6"; then npm install -g bower; npm install; bower install; fi

script:
  - phpunit
  - if php -v | grep -q "PHP 5.6"; then gulp karma; fi
